version: "2"
services:
  database:
    image: mysql:latest
    container_name: timesheetdatabase
    ports:
      - 3366:3306
    environment:
      - MYSQL_DATABASE=mortadhadatabse
      - MYSQL_USER=mortadha
      - MYSQL_PASSWORD=mortadha
      - MYSQL_ROOT_PASSWORD=rootpassword

  web:
    image: mortadha123/timesheetdevops:32
    container_name: timesheetweb
    ports:
      - 8088:8088
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mortadhadatabse?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - DATABASE_NAME=mortadhadatabse
      - DATABASE_PORT=3306
      - DATABASE_USER=mortadha
      - SPRING_DATASOURCE_USERNAME=mortadha
      - SPRING_DATASOURCE_PASSWORD=mortadha
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=mortadha.bouallagui1@esprit.tn
      - GF_SMTP_PASSWORD=Mortaa12683694

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - C:\Users\Administrator\Desktop\prometheus-2.31.1.windows-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
